### Teste do endpoint GET para listar entregas
GET http://localhost:3000/entregas
Content-Type: application/json


### Teste do endpoint POST para cadastrar uma nova entrega
POST http://localhost:3000/entregas
Content-Type: application/json

{ 
  "id": "1",
  "remetente": "Senac Centro",
  "destinatario": "Senac Alecrim",
  "enderecoDestino": "Rua 1, nº 1",
  "dataPrevista": "2025-02-21",
  "status": "pendente"
}

### Pegar produto pelo id
GET  http://localhost:3000/entregas/1
Content-Type: application/json


### Teste com dados incompletos para verificar validação
POST http://localhost:3000/entregas
Content-Type: application/json

{
    "id": "2",
    "remetente": "Senac Centro",
    "destinatario": "Senac Alecrim",
    "enderecoDestino": "Rua 1, nº 1",
  // Faltam os campos: dataPrevista e status
}

### Tesde de atualização pelo id
PUT http://localhost:3000/entregas/1
Content-Type: application/json

{
    "id": "1",
    "novoRemetente": "Senac Centro",
    "novoDestinatario": "Senac Alecrim",
    "novoEnderecoDestino": "Rua 1, nº 1",
    "novaDataPrevista": "2025-02-21",
    "novoStatus": "entregue"
}